#!/usr/bin/env python3
"""Install Scout's git hooks into a target repository.

Usage:
    python scripts/install_hooks.py                     # install into the current repo
    python scripts/install_hooks.py /path/to/other/repo # install into another repo
    python scripts/install_hooks.py --pre-push          # also install the pre-push hook
    python scripts/install_hooks.py --uninstall         # remove Scout hooks
"""

from __future__ import annotations

import argparse
import stat
import subprocess
import sys
from pathlib import Path

# Ensure Unicode output works on Windows terminals
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

_SCOUT_ROOT = str(Path(__file__).resolve().parent.parent)

# ── Hook templates ────────────────────────────────────────────────────────────

_PRE_COMMIT_SCRIPT = f'''\
#!/usr/bin/env python3
# Scout pre-commit hook — auto-generated by scripts/install_hooks.py
# Do not edit manually; re-run install_hooks.py to update.
import sys
sys.path.insert(0, {_SCOUT_ROOT!r})
from backend.hooks.pre_commit import main
sys.exit(main())
'''

# The pre-push hook reads the push ref range from stdin (git protocol).
_PRE_PUSH_SCRIPT = f'''\
#!/usr/bin/env python3
# Scout pre-push hook — auto-generated by scripts/install_hooks.py
import sys, subprocess, pathlib
sys.path.insert(0, {_SCOUT_ROOT!r})

data = sys.stdin.read().strip()
if not data:
    sys.exit(0)

parts = data.split()
if len(parts) < 4:
    sys.exit(0)

local_sha  = parts[1]
remote_sha = parts[3]

# Determine changed files in the push range
ZERO = "0" * 40
range_arg = f"{{remote_sha}}..{{local_sha}}" if remote_sha != ZERO else local_sha
result = subprocess.run(
    ["git", "diff", "--name-only", "--diff-filter=ACMR", range_arg],
    capture_output=True, text=True,
)
files = [str(pathlib.Path(f).resolve()) for f in result.stdout.splitlines() if f.strip()]
if not files:
    sys.exit(0)

try:
    from backend.tools.ruff_runner import run_ruff
    from backend.tools.generic_scan import generic_scan
except ImportError:
    sys.exit(0)

py_files = [f for f in files if f.endswith(".py")]
issues   = (run_ruff(py_files, select="S") if py_files else []) + generic_scan(files)
critical = [i for i in issues if i.get("severity") == "critical"]

if critical:
    print("\\033[31m🚫  Scout pre-push: CRITICAL issues in push range — push blocked\\033[0m")
    for i in critical:
        p = pathlib.Path(i.get("file", "?"))
        print(f"  {{p.name}}:{{i.get('line', '?')}}  [{{i.get('code', '?')}}]  {{i.get('message', '')}}")
    print("\\n  Fix these issues or bypass with: git push --no-verify")
    sys.exit(1)

sys.exit(0)
'''

# ── Helpers ───────────────────────────────────────────────────────────────────

def _git_root(target: str) -> Path:
    try:
        out = subprocess.run(
            ["git", "-C", target, "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, check=True,
        )
        return Path(out.stdout.strip())
    except subprocess.CalledProcessError:
        print(f"Error: {target!r} is not inside a git repository.", file=sys.stderr)
        sys.exit(1)


def _write_hook(hooks_dir: Path, name: str, content: str) -> None:
    path = hooks_dir / name
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if "Scout" in existing:
            print(f"  {name}: updating existing Scout hook")
        else:
            # Preserve non-Scout hook — chain it
            print(f"  {name}: existing non-Scout hook found — chaining")
            content = existing.rstrip() + "\n\n# === Scout (appended) ===\n" + content
    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    print(f"  {name}: ✓")


def _remove_hook(hooks_dir: Path, name: str) -> None:
    path = hooks_dir / name
    if not path.exists():
        print(f"  {name}: not found — skipped")
        return
    content = path.read_text(encoding="utf-8")
    if "Scout" not in content:
        print(f"  {name}: not a Scout hook — skipped")
        return
    path.unlink()
    print(f"  {name}: removed ✓")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Install Scout git hooks into a repository.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "target", nargs="?", default=".",
        help="Path to the target repo (default: current directory)",
    )
    parser.add_argument(
        "--pre-push", action="store_true",
        help="Also install the pre-push hook (checks files in the push range)",
    )
    parser.add_argument(
        "--uninstall", action="store_true",
        help="Remove Scout hooks from the target repo",
    )
    args = parser.parse_args()

    git_root  = _git_root(args.target)
    hooks_dir = git_root / ".git" / "hooks"
    hooks_dir.mkdir(exist_ok=True)

    print(f"Repository : {git_root}")
    print(f"Scout root : {_SCOUT_ROOT}")
    print(f"Hooks dir  : {hooks_dir}")
    print()

    if args.uninstall:
        print("Removing Scout hooks:")
        _remove_hook(hooks_dir, "pre-commit")
        _remove_hook(hooks_dir, "pre-push")
        print("\nDone.")
        return

    print("Installing Scout hooks:")
    _write_hook(hooks_dir, "pre-commit", _PRE_COMMIT_SCRIPT)
    if args.pre_push:
        _write_hook(hooks_dir, "pre-push", _PRE_PUSH_SCRIPT)

    print()
    print("Done. Test with:")
    print("  git commit --allow-empty -m 'test Scout pre-commit hook'")
    if args.pre_push:
        print("  git push --dry-run  # triggers pre-push")


if __name__ == "__main__":
    main()
